#if !canImport(ObjectiveC)
import XCTest

extension CommonParsersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommonParsersTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CommonParsersTests.__allTests__CommonParsersTests),
    ]
}
#endif
